name: Auto_Scraper_Final
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup_Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install_Requests
        run: pip install requests

      - name: Run_Scraper_Script
        env:
          MY_PROXY_URL: ${{ secrets.PROXY_URL }}
        run: python scraper.py

      - name: Upload_Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy
        uses: actions/deploy-pages@v4
