name: Auto Scraper
on:
  push:
    branches: [ main ]
  workflow_dispatch: 

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    # 新增下面这三行，告诉 GitHub 这是 Pages 部署环境
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scraper
        env:
          # 确保这里的 Secret 名字 PROXY_URL 准确无误
          MY_PROXY_URL: ${{ secrets.PROXY_URL }}
        run: |
          python scraper.py

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
